osx_image: xcode12
language: objective-c

before_install:
- gem install xcpretty cocoapods
- cd Example; pod install; cd ..;

script:
- set -o pipefail && xcodebuild build -workspace Example/Beacon\ Example.xcworkspace -scheme 'BeaconExample' -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild build -workspace Example/Beacon\ Example.xcworkspace -scheme 'BeaconExample' -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.4' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild build -workspace Example/Beacon\ Example.xcworkspace -scheme 'BeaconExample' -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
